### PR TITLE
fix: `useContractRead` & `useContractReads` data instability

### LINKED ISSUE #648: [bug] useContractReads data instability
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

latest

### Current Behavior

useContractReads returns unstable data, equality is always lost despite underlying data being exactly the same

### Expected Behavior

In cases where the underlying data has not changed, for equality to be preserved. 

### Steps To Reproduce

repro below

### Link to Minimal Reproducible Example (CodeSandbox, StackBlitz, etc.)

https://codesandbox.io/s/small-smoke-2i7b0q?file=/src/App.js

### PR DESCRIPTION
**Pull request by jxom**
## Description

Fixes #648.

### CODE REVIEW

File: packages/react/src/hooks/contracts/useContractRead.ts [hunk 1]
```diff
@@ -121,40 +121,12 @@ export function useContractRead({
...
-    chainId,
-    client,
-    contractInterface,
-    enabled,
-    functionName,
-    overrides,
-    queryKey_,
-    watch,
-  ])
+  useInvalidateOnBlock({ enabled: watch && !cacheOnBlock, queryKey: queryKey_ })
```
Comment (jxom) [inline packages/react/src/hooks/contracts/useContractRead.ts:124]: The old implementation was also refetching on `provider` changes, but we are already checking that in our query key (via chain id). I have refactored this to "invalidate on new block" if `watch & !cacheOnBlock` is truthy.

**Comment by matthewlilley** [comment]
I'm not super familair with changesets yet, I've been meaning to dig into it a bit more for our own use, but I've seen when changesets are added that pre-release versions are immediately published. I wonder if you'd be able to set that up for wagmi. Would be super useful.

**Comment by tmm** [comment]
Great idea! We can set up [Snapshot Releases](https://github.com/changesets/changesets/blob/main/docs/snapshot-releases.md) to do this. There's some [work in progress](https://github.com/changesets/changesets/issues/855) that will make this even easier to set up. Looks like it's moving quickly so can prepare a PR for setting this up.

File: packages/react/src/hooks/utils/useInvalidateOnBlock.ts [hunk 2]
```diff
@@ -0,0 +1,30 @@
...
+  React.useEffect(() => {
+    if (!enabled) return
+    if (blockNumber === startBlock.current) return
+    if (!startBlock.current) {
+      startBlock.current = blockNumber
+      return
+    }
+
+    queryClient.invalidateQueries(queryKey)
+  }, [blockNumber, enabled, queryClient, queryKey])
```
Comment (tmm) [inline packages/react/src/hooks/utils/useInvalidateOnBlock.ts:29]: If `useBlockNumber`s implementation was updated slightly, we could use the `onSuccess` callback instead of a separate effect here.

File: packages/react/src/hooks/utils/useInvalidateOnBlock.ts [hunk 3]
```diff
@@ -0,0 +1,30 @@
+import * as React from 'react'
+import { QueryKey, useQueryClient } from 'react-query'
+
+import { useBlockNumber } from '../network-status'
+
+export function useInvalidateOnBlock({
```
Comment (tmm) [inline packages/react/src/hooks/utils/useInvalidateOnBlock.ts:6]: Think it's useful to have a basic test that checks the query cache between new blocks?

Not easy to do with our current testing setup, but maybe at least we should add a `test.todo`.

**Review by tmm — COMMENTED** [review]
Want to move the `deepEqual` implementation into `@wagmi/core`? Seems useful to have an ethers-compatible implementation live there (e.g. for dealing with things like `Result`). Also, should we expose it from `wagmi` too - now that it's a default for `isDataEqual`?

File: packages/react/src/hooks/utils/useInvalidateOnBlock.ts (hunk 2 above)
Comment (jxom) [reply packages/react/src/hooks/utils/useInvalidateOnBlock.ts]: Good idea! Updated, and now the implementation is more basic 👌

File: packages/react/src/hooks/network-status/useBlockNumber.ts [hunk 4]
```diff
@@ -11,6 +11,8 @@ import { useProvider, useWebSocketProvider } from '../providers'
 import { useChainId, useQuery } from '../utils'
 
 type UseBlockNumberArgs = Partial<FetchBlockNumberArgs> & {
+  /** Function fires when a new block is created */
+  onBlock?: (blockNumber: number) => void
```
Comment (tmm) [inline packages/react/src/hooks/network-status/useBlockNumber.ts:15]: pretty awesome

**Review by tmm — APPROVED** [review]
