### PR TITLE
fix: fix multicall returning nullish data for all calls unexpectedly

### LINKED ISSUE #645: [bug] useContractReads returning [null] or undefined data unexpectedly
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

latest

### Current Behavior

There was a previous issue which was closed but had reported the same issue. Maybe there is some human error here but I'm struggling to find it. I've added a repro to illustrate this one with the same data.

### Expected Behavior

Work

### Steps To Reproduce

repro attached

### Link to Minimal Reproducible Example (CodeSandbox, StackBlitz, etc.)

https://codesandbox.io/s/pensive-danny-fzwj5g?file=/src/App.js

### Anything else?

We are migrating a large amount of our codebase from redux multicall to wagmi multicall, but have run into a number of issues so far so we are halting and will help illustrate them until there is more stability.

An example of this hook migration from redux multicall to wagmi multicall.

Screenshot_272

### PR DESCRIPTION
**Pull request by jxom**
Fixes #645

## Description

When a contract method returned zero data (`0x`) for any call in a multicall, this would cause the function to throw an error, resulting in the multicall returning nullish data unexpectedly. This PR guards for the case where a call could return zero data, and warns the user that the function does not exist on the targeted contract.

### CODE REVIEW

File: packages/core/src/actions/contracts/multicall.ts [hunk 1]
```diff
@@ -93,6 +94,18 @@ export async function multicall<Data extends any[] = Result[]>({
...
     >contracts[i]
+
+    if (returnData === '0x') {
+      const err = new ContractMethodNoDataError({
+        addressOrName,
+        blockExplorer: chain.blockExplorers?.default,
+        functionName,
+      })
+      if (!allowFailure) throw err
+      console.warn(err.message)
```
Comment (jxom) [inline packages/core/src/actions/contracts/multicall.ts:105]: thought it would be nice to give feedback to the user as to why this is happening. though understand it could bloat the console especially if these errors are expected (i.e. a derived address that is non-existent). wonder if this is okay? or should it be under a flag? or just remove it altogether?

File: packages/react/src/hooks/contracts/useContractReads.ts [hunk 2]
```diff
@@ -20,29 +20,44 @@ export type UseContractReadsConfig = QueryConfig<ReadContractsResult, Error> &
...
       overrides,
     },
   ] as const
 
+const queryKeyHashFn = ([queryKey_]: ReturnType<typeof queryKey>) => {
+  const { contracts, ...rest } = queryKey_
+  const contracts_ = contracts?.map((contract) => {
+    // Exclude the contract interface from the serialized query key.
+    // eslint-disable-next-line @typescript-eslint/no-unused-vars
+    const { contractInterface, ...rest } = contract
```
Comment (jxom) [inline packages/react/src/hooks/contracts/useContractReads.ts:43]: `contractInterface` bloated the hashed query key and caused a weird bug where data would persist on the wrong query key.

File: packages/react/src/hooks/contracts/useContractReads.ts [hunk 3]
```diff
@@ -20,29 +20,44 @@ export type UseContractReadsConfig = QueryConfig<ReadContractsResult, Error> &
...
 }: QueryFunctionArgs<typeof queryKey>) => {
   return readContracts({
+    allowFailure,
     contracts,
     overrides,
   })
 }
 
 export function useContractReads({
+  allowFailure = true,
```
Comment (jxom) [inline packages/react/src/hooks/contracts/useContractReads.ts:60]: should also include `allowFailure` as a prop here.

File: packages/core/src/actions/contracts/multicall.ts [hunk 4]
```diff
@@ -93,14 +94,31 @@ export async function multicall<Data extends any[] = Result[]>({
     const { addressOrName, contractInterface, functionName } = <
       MulticallContract
     >contracts[i]
+
+    if (returnData === '0x') {
```
Comment (jxom) [inline packages/core/src/actions/contracts/multicall.ts:98]: this is the guts of this PR

File: packages/core/src/actions/contracts/multicall.ts (hunk 1 above)
Comment (tmm) [reply packages/core/src/actions/contracts/multicall.ts:105]: Good point! There are a few places where we display warning messages already. Might be nice to make this configurable at some point (e.g. you can switch off warnings, only show in dev mode, etc.).

File: packages/core/src/errors.ts [hunk 5]
```diff
@@ -110,6 +111,34 @@ export class ConnectorNotFoundError extends Error {
   message = 'Connector not found'
 }
 
+export class ContractMethodNoResultError extends Error {
```
Comment (tmm) [inline packages/core/src/errors.ts:114]: Should we export this from the various `index.ts`s like the other errors?

Comment (jxom) [reply packages/core/src/errors.ts:114]: Yes!
